services:
  app:
    build: .
    container_name: my-typescript-app
    command: npm run start
    ports:
      - "3000:3000" # mapeia porta do servidor
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
